<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Goto Home</name>
   <tag></tag>
   <elementGuidId>4f2d8e7c-cff3-4885-af20-a054e582f424</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#home</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='home']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6bc83f23-07ce-4c43-9b12-110fa79af8ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>2c21133f-5d23-43b1-a61e-72cd3db6071b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>home</value>
      <webElementGuid>54d136b7-ed5d-49e5-8b48-cd33d42aec74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button is-link</value>
      <webElementGuid>aef51079-43a7-402a-888c-af3b692b7ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1c425777-1e2b-47da-932b-ef77002776e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Goto Home</value>
      <webElementGuid>f9f0988c-7345-4304-9b3f-9a5e5120f37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)</value>
      <webElementGuid>1f99631f-73e7-46d9-9946-97f31fedfaaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='home']</value>
      <webElementGuid>92f5f177-8ea8-4653-a7e8-deb75a5c0762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Goto Home and come back here using driver command'])[1]/following::button[1]</value>
      <webElementGuid>5bcf8170-f4de-4266-a5b5-2b982cc08871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Button'])[1]/following::button[1]</value>
      <webElementGuid>b11185bc-f1fd-4f25-99b2-0e18cdd6ec08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get the X &amp; Y co-ordinates'])[1]/preceding::button[1]</value>
      <webElementGuid>5c7cf76e-b638-414e-97c4-affc7d6274e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find Location'])[1]/preceding::button[1]</value>
      <webElementGuid>d726fd40-c382-4244-bfcb-3875146f38f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Goto Home']/parent::*</value>
      <webElementGuid>f36098ff-c6a0-49ed-b22b-081ad0ba0bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>597f9113-d110-4c2d-b166-a26b9a12fb36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'home' and (text() = 'Goto Home' or . = 'Goto Home')]</value>
      <webElementGuid>91dd845b-d1f6-4782-8479-d1426d27a75e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
