<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Disabled</name>
   <tag></tag>
   <elementGuidId>cae8b1ed-1c68-4391-bcfd-f34946e49613</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isDisabled</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='isDisabled']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>824af62f-26c1-407e-a91f-dac816f60597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Disabled button</value>
      <webElementGuid>545c27e6-6ef7-4a5b-b101-451664fd4106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isDisabled</value>
      <webElementGuid>f4a67673-0587-4115-a321-b482f7fd1873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button is-info</value>
      <webElementGuid>e9a9c6e2-1a76-44b7-97c5-84dc903fe1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Disabled</value>
      <webElementGuid>77811695-d17c-4249-a37a-8c9ea9f48c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[1]/app-root[1]/app-buttons[1]/section[@class=&quot;section has-background-white-ter&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;columns is-multiline&quot;]/div[@class=&quot;column is-7-desktop is-8-tablet&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-content&quot;]/div[@class=&quot;field&quot;]/div[@class=&quot;control&quot;]/button[@id=&quot;isDisabled&quot;]</value>
      <webElementGuid>fee309be-48c4-487e-8710-189868a424e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='isDisabled']</value>
      <webElementGuid>b011405c-5c28-42c6-9677-038e98e1cbca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm button is disabled'])[1]/following::button[1]</value>
      <webElementGuid>c9953eb0-bea1-4063-971a-1ff81ec6fb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How tall &amp; fat I am?'])[1]/following::button[1]</value>
      <webElementGuid>5d106dc5-5d94-4c91-972e-e341c22fd523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click and Hold Button'])[1]/preceding::button[1]</value>
      <webElementGuid>c77e1701-9b30-42a9-8bab-f99a31f8f508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Button Hold!'])[1]/preceding::button[1]</value>
      <webElementGuid>b1c15898-2cf1-4bb0-9458-05abdd53ea3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Disabled']/parent::*</value>
      <webElementGuid>08d7931c-dc38-471f-b835-0cf251952747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>1e790d9b-e1a6-4cc8-a15f-5755ff8dae08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Disabled button' and @id = 'isDisabled' and (text() = 'Disabled' or . = 'Disabled')]</value>
      <webElementGuid>63d02f58-079b-43a4-a806-f42c489a0e2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
