<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Find Location</name>
   <tag></tag>
   <elementGuidId>70494ec9-e597-493a-b1b9-36634b1dced8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#position</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='position']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eb244e6b-fc46-4b54-b525-24147915e87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>position</value>
      <webElementGuid>167e587f-d6c6-4038-9551-3d5ba2e25941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button is-link is-outlined</value>
      <webElementGuid>5349fbe9-f117-4c47-a505-27ac51e54ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find Location</value>
      <webElementGuid>33bc24ac-2c3b-40e0-aeb9-12af84519f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;position&quot;)</value>
      <webElementGuid>02b0ad5f-9c61-4390-a2f7-056eece2c939</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='position']</value>
      <webElementGuid>f8980bea-7c2f-4c23-8150-c97f2009ef4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get the X &amp; Y co-ordinates'])[1]/following::button[1]</value>
      <webElementGuid>d63cc704-3e9a-4e4f-8fde-292e388ef34a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Goto Home'])[1]/following::button[1]</value>
      <webElementGuid>c2487c3c-e8a8-4970-aa3a-cf859345aaa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find the color of the button'])[1]/preceding::button[1]</value>
      <webElementGuid>0b5f7396-4830-422d-8617-361098bfc7e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is my color?'])[1]/preceding::button[1]</value>
      <webElementGuid>fb7f93d6-0514-4789-b48e-559bd1453e46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Find Location']/parent::*</value>
      <webElementGuid>c608487b-8a9b-42ea-871f-251f27050a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>914b8ba1-c3b0-4ee5-affe-4dc7038637ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'position' and (text() = 'Find Location' or . = 'Find Location')]</value>
      <webElementGuid>ff8c18a0-8cce-4444-88a7-1be4b0190414</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
