<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_Ant-Man</name>
   <tag></tag>
   <elementGuidId>ffe9d968-b891-4eb2-bf8c-4ac247c32f86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[@value='am']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>option[value=&quot;am&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>2abf29f4-7189-4f2c-a5b9-cd24cab0f502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>am</value>
      <webElementGuid>ecff710c-9d28-45bb-88c6-32396cd132a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ant-Man</value>
      <webElementGuid>9de8ed08-8640-4bf9-9b11-d38254a51a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;superheros&quot;)/option[1]</value>
      <webElementGuid>c00ffa82-54dc-4603-ae49-04585bf78ee7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//option[@value='am']</value>
      <webElementGuid>ad962f24-4b42-4bc6-9413-e0d7c80083de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//select[@id='superheros']/option</value>
      <webElementGuid>454dc270-60b5-448b-8d42-966340b0deaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Select your super hero', &quot;'&quot;, 's')])[1]/following::option[1]</value>
      <webElementGuid>84878532-8d77-49b4-a433-45c4b21c7919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the apple using visible text'])[1]/following::option[7]</value>
      <webElementGuid>22339d01-dd33-4abd-a380-d5bb9132e5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the last programming language and print all the options'])[1]/preceding::option[29]</value>
      <webElementGuid>e85ab379-df3a-41a8-bd4a-8895dda0948c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select India using value &amp; print the selected value'])[1]/preceding::option[34]</value>
      <webElementGuid>0a3b7680-2046-44f8-9cd1-4316d10be7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ant-Man']/parent::*</value>
      <webElementGuid>e5eca9cd-6000-415c-8817-b4f27df48632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select/option</value>
      <webElementGuid>82b9f54a-fb1e-4918-a453-3aefce90585e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//option[(text() = 'Ant-Man' or . = 'Ant-Man')]</value>
      <webElementGuid>a63f6f9d-3546-4c0c-8517-5ad6a2d3176c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
