<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_Aquaman</name>
   <tag></tag>
   <elementGuidId>db0e0f63-0c72-43fa-bb41-71992cf8239f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[@value='aq']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>option[value=&quot;aq&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>800e7a16-ba7d-4003-aa30-efd76ccc960b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>aq</value>
      <webElementGuid>ee36a58d-d06d-44d0-b01a-188e44a4aa40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aquaman</value>
      <webElementGuid>ce0b13f1-aa9b-4fc5-af85-561ea68a448d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;superheros&quot;)/option[2]</value>
      <webElementGuid>fa17f816-006c-4f61-996f-97cd89ecd648</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//option[@value='aq']</value>
      <webElementGuid>08f206e6-d8b7-4fde-a264-e50ebeae70ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//select[@id='superheros']/option[2]</value>
      <webElementGuid>10301182-da5b-4f43-945b-c483ef58bac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Select your super hero', &quot;'&quot;, 's')])[1]/following::option[2]</value>
      <webElementGuid>9f352624-454a-46ac-8d9e-a0f5c3cd0fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the apple using visible text'])[1]/following::option[8]</value>
      <webElementGuid>49edad6b-72cd-41c9-8333-946fcae11a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the last programming language and print all the options'])[1]/preceding::option[28]</value>
      <webElementGuid>cb29a070-832a-46c8-b9b1-87007775d1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select India using value &amp; print the selected value'])[1]/preceding::option[33]</value>
      <webElementGuid>98b4765f-5736-44a3-86ba-e9406cf0442a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aquaman']/parent::*</value>
      <webElementGuid>73cc7776-0864-447a-a478-0815d1791587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select/option[2]</value>
      <webElementGuid>6200a182-aa0d-4866-8887-64df5498caee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//option[(text() = 'Aquaman' or . = 'Aquaman')]</value>
      <webElementGuid>2e7d9719-befb-44d8-b4a3-a60861cbbc36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
