<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ArgentinaBoliviaBrazilChileColombiaEcuadorIndiaParaguayPeruSurinameUruguayVenezuela</name>
   <tag></tag>
   <elementGuidId>ce08f4e3-9891-4353-adf9-4878c54dd928</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='country']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#country</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4afe69f8-cee8-4b97-a0a8-7d4cbd4acb77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>country</value>
      <webElementGuid>4bbb08d1-76fa-4e2e-bc76-a1934585635d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ArgentinaBoliviaBrazilChileColombiaEcuadorIndiaParaguayPeruSurinameUruguayVenezuela</value>
      <webElementGuid>a6bb4e5d-81ed-4a12-a654-a4ac0aa598e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;country&quot;)</value>
      <webElementGuid>cacd44bb-8275-44f0-b6db-a1892068a072</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='country']</value>
      <webElementGuid>9344906a-6a77-4d31-bb5f-8f3f03a17c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select India using value &amp; print the selected value'])[1]/following::select[1]</value>
      <webElementGuid>81bc594e-6426-4716-9512-9a0380161f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the last programming language and print all the options'])[1]/following::select[2]</value>
      <webElementGuid>945c3f1f-72aa-4065-9ef4-c166ddb8b735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click me'])[1]/preceding::select[1]</value>
      <webElementGuid>4109a862-d9ae-4452-af65-3526816dd821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On completion of this exercise, you can learn the following concepts.'])[1]/preceding::select[1]</value>
      <webElementGuid>e6409c0b-a53c-4669-b7bd-0ff07e1a130e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>b433ae84-bae0-4958-b324-dbb2306b1f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'country' and (text() = 'ArgentinaBoliviaBrazilChileColombiaEcuadorIndiaParaguayPeruSurinameUruguayVenezuela' or . = 'ArgentinaBoliviaBrazilChileColombiaEcuadorIndiaParaguayPeruSurinameUruguayVenezuela')]</value>
      <webElementGuid>d924295e-5b99-49b0-9c00-4e54f8adabd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
