<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_JavaScriptJavaPythonSwiftC</name>
   <tag></tag>
   <elementGuidId>f995713d-03bf-4a9a-b78e-38ec98760193</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='lang']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lang</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7e87e2cc-a443-4477-8189-3f4810de0746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lang</value>
      <webElementGuid>9b329b22-8a24-47a8-a085-08812721268c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JavaScriptJavaPythonSwiftC#</value>
      <webElementGuid>743d18fa-01ca-4d82-8cee-2ce02e8b7ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lang&quot;)</value>
      <webElementGuid>064357dd-f818-485a-8263-1c7d3b3f9f07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='lang']</value>
      <webElementGuid>72d76938-c6a9-4186-ac95-3453400b51ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the last programming language and print all the options'])[1]/following::select[1]</value>
      <webElementGuid>88078424-1398-4e91-bf94-43a6c12e4445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Select your super hero', &quot;'&quot;, 's')])[1]/following::select[2]</value>
      <webElementGuid>252208c9-e548-41d5-a617-d9d33cbe14ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select India using value &amp; print the selected value'])[1]/preceding::select[1]</value>
      <webElementGuid>b72c2fcf-e281-48b3-a9ac-b2009c370ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click me'])[1]/preceding::select[2]</value>
      <webElementGuid>c241a276-78da-489f-ae39-2bb105970392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/select</value>
      <webElementGuid>abe6ec86-39bd-43f3-90f1-19193e7e24ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'lang' and (text() = 'JavaScriptJavaPythonSwiftC#' or . = 'JavaScriptJavaPythonSwiftC#')]</value>
      <webElementGuid>037737a5-ba3d-4f40-84e1-8971c0c3ef6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
