<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select FruitAppleMangoOrangeBananaPine Apple</name>
   <tag></tag>
   <elementGuidId>271dfb11-01d4-4291-adf5-472f0e02d369</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fruits']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fruits</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>22d182b0-bfc6-45a0-8b20-979a1dc4e657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fruits</value>
      <webElementGuid>e941f572-3781-4786-ae5e-498e1d51f2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select FruitAppleMangoOrangeBananaPine Apple</value>
      <webElementGuid>332a0fea-7aa5-48d1-ad22-b90c893cfbf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fruits&quot;)</value>
      <webElementGuid>479024ba-a6f9-4ff8-99c5-dc2d9490c43f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fruits']</value>
      <webElementGuid>d39bcda5-1a28-4736-8ba8-472b64f9bb29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the apple using visible text'])[1]/following::select[1]</value>
      <webElementGuid>8a20fbbf-1ce9-4c70-a36c-295bdcfa0da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dropdown'])[1]/following::select[1]</value>
      <webElementGuid>df0a4eca-8eb3-40c2-a415-ab722f791cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Select your super hero', &quot;'&quot;, 's')])[1]/preceding::select[1]</value>
      <webElementGuid>76dd2dc2-8f08-4b2d-9f8c-f81b44b4c019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select the last programming language and print all the options'])[1]/preceding::select[2]</value>
      <webElementGuid>d7843e6f-f824-4399-89a4-cd512a3694cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>515cc947-2843-4a04-b137-fc007a36385d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'fruits' and (text() = 'Select FruitAppleMangoOrangeBananaPine Apple' or . = 'Select FruitAppleMangoOrangeBananaPine Apple')]</value>
      <webElementGuid>bc9c5832-95c8-41a8-9e79-851303307657</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
